version: '3'
services:
  mongo:
    image: "mongo:3.4"
    command: mongod --port 27019
    ports:
      - "27019:27019"
    expose:
      - "27019"  
  store:
    # build: https://github.com/webAutomaticTest/store.git
    image: "wchen001/webefg_storage19"
    ports:
      - "8086:8086"
    depends_on:
      - "mongo"  

volumes:
  screens:
     
   
