version: '3'
services:
  mongo:
    image: "mongo:3.4"
    command: mongod --port 27017
    ports:
      - "27017:27017"
    expose:
      - "27017"  
  store:
    # build: https://github.com/webAutomaticTest/store.git
    image: "wchen001/webefg_storage17"
    ports:
      - "8086:8086"
    depends_on:
      - "mongo"
  front:
    build: 
      context: https://github.com/efgWebTest/efgWebTest.git
      dockerfile: ./front/DockerfileDebug
    image: "wchen001/webefg_front"
    volumes:
      - screens:/var/www/public/img/screen
    ports:
      - 8080:80
    restart: always
    depends_on:
      - "store"  

volumes:
  screens:
     
   
